{% set name = "fuzzytm" %}
{% set version = "2.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FuzzyTM-{{ version }}.tar.gz
  sha256: 1ac04d4de2507cbd107c35b0450468c4f2ef01f8038c2fb6dce1137a2ce7b584

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas
    - scipy
    - pyfume
    - gensim

test:
  imports:
    - FuzzyTM
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ERijck/FuzzyTM
  summary: A Python package for Fuzzy Topic Models
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgruening
